name: deploy to gh-pages

on:
  push:
    branches: [master]
    paths:
      - 'public/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Deploy to gh-pages
        run: npx gh-pages -d public
      
